[project]
name = "{{name}}"
version = "0.1.0"
authors = [
  { name="Christoph Kappestein", email="christoph.kappestein@gmail.com" },
]
description = "{{description}}"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Code Generators",
]
dependencies = [
    "sdkgen-client"
]

[project.urls]
Homepage = "{{github_url}}"
Issues = "{{github_url}}/issues"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["sdk"]
package-dir = {"" = "src"}
